version: '3.8'

services:
  php74fpm:
    container_name: php74fpm  # 指定しないと {Current Dir}_php74fpm_1 と長い名前になってしまう。
    build: ./docker/php
    volumes:
      - ./laravel:/var/www
  nginx:
    container_name: nginx  # 指定しないと {Current Dir}_nginx_1 と長い名前になってしまう。
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./laravel:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php74fpm
  mysql8:
    container_name: mysql8  # 指定しないと {Current Dir}_mysql8_1 と長い名前になってしまう。
    restart: always
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: muro1968
      MYSQL_DATABASE: fxdb
      MYSQL_USER: laravel
      MYSQL_PASSWORD: muro1968
    # MySQL8 から 認証プラグインのデフォルトが cacing_sha2_password になったが
    # 接続元のコンテナが、cacing_sha2_password をサポートしていない場合があるので、mysql_native_password に戻しておく。
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql8_volume:/var/lib/mysql                 # 名前付ボリュームをMySQLのデータDirにマントする。
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf  # my.cnfを配置
      - ./docker/db/ddl:/docker-entrypoint-initdb.d  # テーブル作成DDL
volumes:
  mysql8_volume:
    name: mysql8_volume  # 指定しないと {Current Dir}_mysql8_volume と長い名前になってしまう。

